#!/bin/bash
OUTPUT_FILE="AmpAI_Contratos_E_Estrutura_De_Codigo.md"

echo "---" > $OUTPUT_FILE
echo "type: architecture/contracts" >> $OUTPUT_FILE
echo "project: AmpAI" >> $OUTPUT_FILE
echo "last_autogenerated: $(date +'%Y-%m-%d %H:%M:%S')" >> $OUTPUT_FILE
echo "---" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "# 📂 Mapa Geral de Contratos e Assinaturas de Código (Autogerado)" >> $OUTPUT_FILE
echo "Este arquivo mapeia as funções e contratos de payload para alimentar o contexto do NotebookLM." >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# Varre dinamicamente TODOS os arquivos .js dentro da pasta js/
for file in js/*.js; do
    if [ -f "$file" ]; then
        echo "## 📄 $file" >> $OUTPUT_FILE
        echo "### 🔄 Funções Identificadas:" >> $OUTPUT_FILE
        
        # [ATUALIZAÇÃO v5.0] Captura funções padrão E funções exportadas no objeto window.*
        grep -E "function |window\." "$file" | sed 's/^[ \t]*//' | sed 's/^/- /' >> $OUTPUT_FILE
        
        echo "" >> $OUTPUT_FILE
    fi
done

echo "✅ Mapa de contratos gerado com sucesso!"
