#!/bin/bash
OUTPUT_FILE="AmpAI_Contratos_E_Estrutura_De_Codigo.md"

echo "---" > $OUTPUT_FILE
echo "type: architecture/contracts" >> $OUTPUT_FILE
echo "project: AmpAI" >> $OUTPUT_FILE
echo "last_autogenerated: $(date +'%Y-%m-%d %H:%M:%S')" >> $OUTPUT_FILE
echo "---" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "# 📂 Mapa Geral de Contratos e Assinaturas de Código (Autogerado)" >> $OUTPUT_FILE
echo "Este arquivo mapeia as funções e contratos de payload para alimentar o contexto do NotebookLM." >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

for file in js/*.js; do
    if [ -f "$file" ]; then
        echo "## 📄 $file" >> $OUTPUT_FILE
        echo "### 🔄 Funções Identificadas:" >> $OUTPUT_FILE
        grep -E "function " "$file" | sed 's/function /- /g' | sed 's/ {/ /g' >> $OUTPUT_FILE
        echo "" >> $OUTPUT_FILE
    fi
done
