Write-Host "[AmpAI] Puxando atualizacoes do GitHub (VPS/Rua)..." -ForegroundColor Cyan
git pull origin main --rebase

# =========================================================================
# 0.5 Geração Automática de Contratos Dinâmicos (Nativo PowerShell)
# =========================================================================
Write-Host "[AmpAI] Rastreiando novos modulos JS e gerando contratos..." -ForegroundColor Cyan

$outputFile = ".\AmpAI_Contratos_E_Estrutura_De_Codigo.md"
$date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

@"
---
type: architecture/contracts
project: AmpAI
last_autogenerated: $date
---

# 📂 Mapa Geral de Contratos e Assinaturas de Código (Autogerado)
Este arquivo mapeia as funções e contratos de payload para alimentar o contexto do NotebookLM.
"@ | Out-File -FilePath $outputFile -Encoding utf8 -Force

if (Test-Path ".\js") {
    $jsFiles = Get-ChildItem -Path ".\js" -Filter "*.js"
    foreach ($file in $jsFiles) {
        "`n## 📄 js/$($file.Name)`n### 🔄 Funções Identificadas:" | Out-File -FilePath $outputFile -Encoding utf8 -Append
        
        # Lê as funções puras e as amarradas ao window.*
        $matches = Select-String -Path $file.FullName -Pattern "function |window\."
        foreach ($match in $matches) {
            $cleanLine = "- " + $match.Line.Trim()
            $cleanLine | Out-File -FilePath $outputFile -Encoding utf8 -Append
        }
    }
}
Write-Host " -> Mapa de contratos gerado com sucesso!" -ForegroundColor DarkGray

# =========================================================================
# 0. Definição de Rotas Base
# =========================================================================
$targetFolder = "G:\Meu Drive\AmpAI_NotebookLM"
# Caminho EXATO da sua subpasta dedicada ao projeto no Obsidian
$obsidianAmpAIFolder = "C:\Users\ACER\Desktop\Thiago_2.0\03-Trabalho\200 Projetos Ativos\Principais\AmpAI"

# =========================================================================
# 1. Fluxo Automático do Mapa de Contratos e README
# =========================================================================
$sourceContratos = ".\AmpAI_Contratos_E_Estrutura_De_Codigo.md"
if (Test-Path $sourceContratos) {
    Copy-Item -Path $sourceContratos -Destination (Join-Path $targetFolder "AmpAI_Contratos_E_Estrutura_De_Codigo.txt") -Force
}

$sourceReadme = ".\README.md"
if (Test-Path $sourceReadme) {
    Copy-Item -Path $sourceReadme -Destination (Join-Path $targetFolder "README.txt") -Force
}

# =========================================================================
# 2. Fluxo Automático: Matriz de Governança (Agentes)
# =========================================================================
$filesToSync = @("AGENTS.md", ".CEO.txt", ".CTO.txt", ".Engenheiro Eletricista.txt", ".Hermes Executive Dev.txt", ".Senior QA-Security.txt", ".Senior_Backend_Dev.txt", ".Senior_Frontend_Dev.txt")
Write-Host "[AmpAI] Sincronizando Matriz de Governanca Multi-Agentes para o Google Drive..." -ForegroundColor Magenta

foreach ($file in $filesToSync) {
    $sourcePath = Join-Path -Path ".\.github\workflows" -ChildPath $file
    if (Test-Path $sourcePath) {
        $destPath = Join-Path -Path $targetFolder -ChildPath $file.Replace(".md", ".txt")
        # Cópia binária preserva UTF-8 integralmente [cite: 191]
        Copy-Item -Path $sourcePath -Destination $destPath -Force 
    }
}

# =========================================================================
# 3. Fluxo Inverso - Varredura Automática do Obsidian -> Git -> Drive
# =========================================================================
Write-Host "[AmpAI] Lendo subpasta do Obsidian (Varredura Automatica)..." -ForegroundColor Cyan

if (!(Test-Path ".\docs")) { New-Item -ItemType Directory -Path ".\docs" | Out-Null }

if (Test-Path $obsidianAmpAIFolder) {
    # Lê automaticamente TODOS os arquivos .md que existirem dentro dessa subpasta
    $obsidianFiles = Get-ChildItem -Path $obsidianAmpAIFolder -Filter "*.md" -File -Recurse

    foreach ($file in $obsidianFiles) {
        $sourceDoc = $file.FullName
        $docName = $file.Name
        
        # A) Copia para a pasta docs/ local para fazer o backup no Git
        Copy-Item -Path $sourceDoc -Destination (Join-Path ".\docs" $docName) -Force
        
        # B) Converte para .txt via cópia binária e manda pro Google Drive
        $driveDest = Join-Path $targetFolder $docName.Replace(".md", ".txt")
        Copy-Item -Path $sourceDoc -Destination $driveDest -Force
        
        Write-Host " -> Espelhado com sucesso: $docName" -ForegroundColor DarkGray
    }
}
else {
    Write-Host " [Aviso] Pasta do Obsidian não encontrada: $obsidianAmpAIFolder" -ForegroundColor Yellow
}

# =========================================================================
# 4. Auto-Commit para o GitHub (A Fonte da Verdade)
# =========================================================================
Write-Host "[AmpAI] Salvando documentacao humana na nuvem (GitHub)..." -ForegroundColor Magenta
git add .\docs\*
git commit -m "docs: atualizacao automatica da pasta AmpAI do Obsidian via sync.ps1"
git push origin main

Write-Host "[AmpAI] Loop Semantico Trilateral Concluido! Ecossistema 100/100." -ForegroundColor Green
