#!/bin/bash
# AmpAI Sincronizador para Linux (VPS)

echo "[AmpAI] Puxando atualizacoes do GitHub (VPS/Rua)..."
git fetch origin main
git reset --hard origin/main

# =========================================================================
# 0.5 Geração Automática de Contratos Dinâmicos
# =========================================================================
echo "[AmpAI] Rastreiando novos modulos JS e gerando contratos..."
OUTPUT_FILE="./AmpAI_Contratos_E_Estrutura_De_Codigo.md"
DATE=$(date +"%Y-%m-%d %H:%M:%S")

cat <<EOF > "$OUTPUT_FILE"
---
type: architecture/contracts
project: AmpAI
last_autogenerated: $DATE
---

# 📂 Mapa Geral de Contratos e Assinaturas de Código (Autogerado)
Este arquivo mapeia as funções e contratos de payload para alimentar o contexto do NotebookLM.
EOF

if [ -d "./js" ]; then
    for file in ./js/*.js; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            echo -e "\n## 📄 js/$filename\n### 🔄 Funções Identificadas:" >> "$OUTPUT_FILE"
            grep -E "function |window\." "$file" | while read -r line; do
                # remove leading spaces
                cleanLine=$(echo "$line" | sed 's/^[ \t]*//')
                echo "- $cleanLine" >> "$OUTPUT_FILE"
            done
        fi
    done
fi
echo " -> Mapa de contratos gerado com sucesso!"

# =========================================================================
# 0. Definição de Rotas Base
# =========================================================================
# O diretório do Google Drive na VPS usa o Rclone. O remote configurado deve chamar 'gdrive:'
TARGET_FOLDER="gdrive:AmpAI_NotebookLM"
LOCAL_DOCS_FOLDER="./docs"

# =========================================================================
# 1. Fluxo Automático do Mapa de Contratos e README
# =========================================================================
if [ -f "$OUTPUT_FILE" ]; then
    rclone copyto "$OUTPUT_FILE" "$TARGET_FOLDER/AmpAI_Contratos_E_Estrutura_De_Codigo.txt"
fi

if [ -f "./README.md" ]; then
    rclone copyto "./README.md" "$TARGET_FOLDER/README.txt"
fi

# =========================================================================
# 2. Fluxo Automático: Matriz de Governança (Agentes)
# =========================================================================
FILES_TO_SYNC=("AGENTS.md" ".CEO.txt" ".CTO.txt" ".Engenheiro Eletricista.txt" ".Hermes Executive Dev.txt" ".Senior QA-Security.txt" ".Senior_Backend_Dev.txt" ".Senior_Frontend_Dev.txt")
echo "[AmpAI] Sincronizando Matriz de Governanca Multi-Agentes para o Google Drive..."

for file in "${FILES_TO_SYNC[@]}"; do
    sourcePath="./.github/workflows/$file"
    if [ -f "$sourcePath" ]; then
        destName="${file//.md/.txt}"
        rclone copyto "$sourcePath" "$TARGET_FOLDER/$destName"
    fi
done

# =========================================================================
# 3. Fluxo Docs as Code - Sincronização da pasta docs/ local -> Drive
# =========================================================================
echo "[AmpAI] Sincronizando documentacao local (Docs as Code)..."

if [ -d "$LOCAL_DOCS_FOLDER" ]; then
    find "$LOCAL_DOCS_FOLDER" -type f -name "*.md" | while read -r sourceDoc; do
        docName=$(basename "$sourceDoc")
        destName="${docName//.md/.txt}"
        rclone copyto "$sourceDoc" "$TARGET_FOLDER/$destName"
        echo " -> Espelhado com sucesso: $docName"
    done
fi

# =========================================================================
# 4. Auto-Commit para o GitHub (A Fonte da Verdade)
# =========================================================================
echo "[AmpAI] Salvando projeto e documentacao na nuvem (GitHub)..."
git add .
git commit -m "docs/chore: atualizacao automatica (Docs as Code) via sync.sh na VPS"
git push origin main

echo "[AmpAI] Loop Semantico Trilateral Concluido! Ecossistema 100/100."
